version: '3'

services:
  web:
    container_name: web-test-local
    build:
      context: .
    volumes:
    - ./src:/app/src
    - ./storage/media:/app/storage/media
    - ./migrations:/app/migrations

    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - test-local
    command: bash -c "alembic upgrade head && uvicorn src.main:app"


  nginx:
    container_name: nginx-test-local
    image: nginx:latest
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - ./config/nginx-local.conf:/etc/nginx/conf.d/default.conf:ro
      - ./storage/media:/app/storage/media:ro
    networks:
      - test-local

  db:
    container_name: db-test-local
    image: postgres:15-alpine
    env_file:
      - .env.db
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      - test-local
    volumes:
      - postgres-data-local:/var/lib/postgresql/data/


volumes:
  postgres-data-local:

networks:
  test-local:
    driver: bridge
